### ISSUE TITLE
Does not work on Win 10 with Steelseries Nimbus

### ISSUE THREAD

**Issue by Levanth** [Axadiw/MFIGamepadFeeder#1] opened 2015-12-07 20:59 UTC
I did everything as you said in your Readme, my Steelseries Nimbus still won't work, neither in TocaEdit nor in JoyMonitor from vJoy

**Comment by Axadiw** [comment] 2016-01-17 11:20
Could you describe what problems are occuring to you?

**Comment by Levanth** [comment] 2016-01-17 11:25
Well the Feeder recognizes the gamepad but it does not send any button presses.

**Comment by Axadiw** [comment] 2016-01-17 13:35
How are you connecting the gamepad to the PC. Cable or bluetooth?

**Comment by Levanth** [comment] 2016-01-17 14:16
I tried both, same Problem either way

**Comment by Axadiw** [comment] 2016-01-17 15:12
Could you post the name of the gamepad you're choosing? Does the vJoy Monitor show anything when pressing gamepad buttons?

**Comment by Levanth** [comment] 2016-01-17 17:59
Its the Steelseries Nimbus and no it won't show anything.

**Comment by Axadiw** [comment] 2016-01-18 07:58
Yes, but I'm asking what's the name of the selected gamepad in MFIGamepadFeeder. Maybe you could post a screenshot?

**Comment by Levanth** [comment] 2016-01-24 00:44
It shows as SteelSeries Nimbus (Vendor ID: 4152, Product ID: 5152, 
Product version: 1, Serial Number: )

**Comment by Axadiw** [comment] 2016-01-24 11:28
Are you sure that you're connecting via bluetooth, not via cable? In this issue: https://github.com/Axadiw/MFIGamepadFeeder/issues/3

It's shown that "SteelSeries Nimbus (Vendor ID: 4152, Product ID: 5152)" is gamepad representation while it's connected via cable. Do you have other devices on the list available in the feeder? For me it hans't any appropriate name, and it's Vendor ID was 65535

**Comment by Levanth** [comment] 2016-01-24 13:20
This is via Cable, when I try via Bluetooth it won't show up at all.

**Comment by Axadiw** [comment] 2016-01-24 13:25
When using bluetooth only, have you tried to add manually the device in windows devices manager or like this: http://windows.microsoft.com/en-gb/windows-10/getstarted-connect-to-bluetooth-devices  ?

**Comment by Axadiw** [comment] 2016-01-24 13:26
after connecting the gamepad via devices manager, it should show up in the MFIGamepadFeeder with Vendor ID = 65535

**Comment by Levanth** [comment] 2016-01-24 13:31
Since I reinstalled my WIndows the other Day I have to download the newest Drivers for the Bluetooth Dongle, I will try again when I got them installed

**Comment by Levanth** [comment] 2016-01-24 16:26
Now I can't connect my Nimbus with Windows, it works on iOS and Mac but I cannot connect it to my PC...

**Comment by BJClark** [comment] 2016-01-24 16:38
My nimbus pairs fine with Windows over Bluetooth but no device shows up in the feeder app. If I plug it in over usb, it shows up in the app but I don't see any input in vJoy monitor.

**Comment by Axadiw** [comment] 2016-01-24 16:38
have you tried unpairing the Nimbus from the iOS and Mac first?

**Comment by Levanth** [comment] 2016-01-24 16:46
Yes, when I turn it on it blinks like it is when it's pairing.
Does the Feeder only work on Bluetooth?

**Comment by Levanth** [comment] 2016-01-24 16:59
@BJClark over usb it's the same for me

**Comment by Axadiw** [comment] 2016-01-24 17:02
Yes, it works only via bluetooth. When you're connecting via cable, the driver doesn't send any commands after button presses. Only bluetooth version of the driver works correctly.

**Comment by Levanth** [comment] 2016-01-24 17:04
So I checked now if my Bluetooth Dongle is broken, my BT-Headset connects fine, so it's the Nimbus which don't want to connect. Any Suggestions?
I turn it on press the BT-Button for a few seconds to let it be in pair-mode but it won't show up on my PC

**Comment by BJClark** [comment] 2016-01-24 17:07
Can you explain further how you are pairing the nimbus over Bluetooth so that it shows up in the feeder app?

**Comment by BJClark** [comment] 2016-01-24 18:51
I repaired the nimbus over Bluetooth, and it now shows up in the device list (correctly identified). When I hit refresh, the message is "Sequence contains no elements".

http://imgur.com/a/cMoaV

**Comment by Levanth** [comment] 2016-01-24 19:24
Do you have the Nimbus also plugged in over USB? Because your Vendor ID and Product ID are the same as mine when I connect via USB

**Comment by BJClark** [comment] 2016-01-24 20:44
I have also tried it that way. Maybe it's left over from that? I will try to go in and reset everything and post the list of devices when I get a minute.

**Comment by pjpalomaki** [comment] 2016-01-26 15:53
I'm on Win 7 and my Nimbus doesn't show in the "Gamepad devices" list at all after pairing with Bluetooth. I even 'forget device' in Apple TV and tried again with no luck. I can see it if I plug it in via cable, but not with Bluetooth...

http://i.imgur.com/ZFEhdHY.jpg

I'm on a MacBook Pro Retina, Bootcamp Win 7 Ultimate.. Other BT Devices pair and work fine.

**Comment by OzBill** [comment] 2016-06-15 00:57
I've having an issue on Windows 10 with the Nimbus. The Nimbus connects via Bluetooth OK, and is recognised by Windows.
 vJoy runs fine, and MFI Gamepad Feeder says;

15/06/2016 12:13:12 AM: Using Shaul Eizikovich vJoy - Virtual Joystick (Vendor ID: 4660, Product ID: 48813, Product version: 534, Serial Number: 2.1.6), vJoy 1, configuration file: Configs\Nimbus.mficonfiguration
15/06/2016 12:13:12 AM: Successfully initialized gamepad

So that seems OK. 
vJoy monitor does not show **any** response from the Nimbus however.
I don't know if this is the issue, but I can't find the config file - it's not in "C:\Users\Admin\AppData\Local" or "C:\Program Files\vJoy" or the sub-folders x64 or x86.

I should also mention that Steam sees a vJoy device but all buttons have "---" assigned to them 

Any assistance you can provide would be appreciated.

Cheers

Bill

**Comment by nickdiacre** [comment] 2016-08-01 13:23
I can confirm this doesn't work for me either... Win10, connected via bluetooth vendor id is 65535. It says successfully initialised gamepad, but no keypresses come through on the monitor.

Would love to know if there is a solution, FWIW win10 does not seem to load up any kind of driver... is it supposed to?

**Comment by Tonyt123** [comment] 2016-10-01 03:14
Same issue here as dogboy23.  Win10 Nimbus connects to bluetooth, shows up in my bluetooth settings, I choose vendor  65535, with Nimbus config file and vjoy id as 1, click Refresh and it say I am ready to use the gamepad, but nothing works when I go to a game of the vjoy monitor.  All I want to do is game a bit.

**Comment by paulodelgado** [comment] 2016-10-07 17:55
Its working fine for me.  Make sure you don't close the Feeder app (just minimize it, it'll go to the tray).  Then go to your emulator and setup your input.  Took me a while to figure out all this.

**Comment by hc3490** [comment] 2016-10-09 15:10
This does not appear to work with vJoy 2.1.7.7-260916, I installed the older build 2.1.6-081015 and it's now working.

**Comment by n0rpie** [comment] 2016-12-09 13:31
Doesn't work at all. Didn't work when using the older 2.16 build of vjoy either. Will you look into this?  Does it still work for anyone?

**Comment by Axadiw** [comment] 2016-12-10 00:37
Actually it was working fine on vJoy 2.1.6 without any problem.

Currently I'm working on major update to the app that is including integration with https://github.com/shauleiz/vGen interface that will allow to emulate X360 controller directly.

VJoy wouldn't be necessary anymore

**Comment by n0rpie** [comment] 2016-12-10 06:41
Do you have download link for the 2.1.6 because the one I found didn't work. It just gives me no input whatsoever . 

Why is vJoy needed right now? Is there any alternative to vJoy one could try?

**Comment by pjpalomaki** [comment] 2016-12-10 12:44
@Axadiw Excellent news! Let me know when you have an alpha/beta working, would love to give it a go.

By the way I got Nimbus working fine in the end on the current version.

**Comment by n0rpie** [comment] 2016-12-10 13:59
@pjpalomaki how? Please help

**Comment by n0rpie** [comment] 2016-12-10 14:44
also: when im trying to pair nimbus with win it is asking for password? what did you do to pair them?

**Comment by Saklad5** [comment] 2016-12-10 21:05
@n0rpie Are you using a virtual machine? Due to the way many of them work, Windows may ask for a password even when none exists. Just leave it blank and click through.

**Comment by Saklad5** [comment] 2016-12-10 21:09
Just to be clear, @pjpalomaki, you got it working on your rMBP under vJoy 2.1.6? I’m trying to get my Nimbus working on my own rMBP, which is running Windows 10 through VMWare Fusion.

**Comment by n0rpie** [comment] 2016-12-10 21:31
@Saklad5 No im not using any virtual machine. Does Numbus require higher bluetooth version than 2.0 perhaps? because i think my bluetooth device says it's only 2.0

ive tried plenty different versions and it's not having any of it. It just says "failed to open device" :(

EDIT: i can pair it but the nimbus goes to "sleep" and disconnects after a while...

**Comment by pjpalomaki** [comment] 2016-12-11 00:11
@n0rpie & @Saklad5 I can't verify the version at the moment as I only run win on bootcamp (MacBook Pro 15" Retina Mid 2012) and I don't want to log out of OSX but I had it running fine a while back, haven't used it since.. Have you guys installed Microsoft Xbox software? Could @Axadiw confirm if the xbox drivers are required (I assume they are)?

**Comment by Axadiw** [comment] 2016-12-11 12:32
Current version of MFIGamepadFeeder (1.0.1) doesn't require Xbox drivers.

**Comment by Axadiw** [comment] 2016-12-17 22:15
If you're interested in the current status of MFIGamepadFeeder, I've uploaded sneak peek of 2.0 release that will emulate Xbox controllers:
https://github.com/Axadiw/MFIGamepadFeeder/releases/tag/2.0.0-alpha1


Please test this version and tell if it's working for you :)

**Comment by pjpalomaki** [comment] 2016-12-17 22:43
@Axadiw Excellent! Will try and test it out asap, between christmas rushes!

**Comment by Saklad5** [comment] 2016-12-18 00:36
@Axadiw The problem I ran into was MFIGamepadFeeder not recognizing the device at all, even though it was paired via Bluetooth and everything. Do you have any reason to think it might work on the new version given otherwise-identical conditions?

I was running Windows 10 through VMWare Fusion, but that would only matter if the COMPUTER needed to advertise services. Windows 10 should be able to see Bluetooth devices advertising to it just fine. I mention this on the off-chance that it _is_ a problem, as I don’t want to you to waste time debugging a problem that isn’t being caused by your software at all.

**Comment by Axadiw** [comment] 2016-12-18 10:44
@Saklad5 Unfortunately if MFIGamepadFeeder doesn't recognize your gamepad, there not much we can do :(

Actially I've been trying to test this software under Parallels on MBP Mid 2015, but system wasn't able to find my Nimbus even in bluetooth pairing screen (in windows control panel). Currently I'm able to run MFIGamepadFeeder only natively on Windows PC.

**Comment by Axadiw** [comment] 2016-12-22 11:03
Final version of 2.0 is already published. I guess that it should fix all the problems listed in this issue.

**Closed as completed by Axadiw** 2016-12-22 11:03 UTC
Labels: bug

**Comment by n0rpie** [comment] 2016-12-27 07:58
Will try it later thank you so much for your work
